Repository AY2223S1-CS2103T-W09-2/tp, pull requests merged in 2022-10, with the labels that each got.

#65 Add DateTimeParser
  src/main/java/seedu/address/logic/parser/DateTimeParser.java
  src/test/java/seedu/address/logic/parser/DateTimeParserTest.java
Labels: type.task

#77 Update help command url
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.task, severity.Low

#81 Update UI
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/calendar.png
  src/main/resources/images/clock.png
  src/main/resources/images/contact_book_32.png
  src/main/resources/images/email.png
  src/main/resources/images/home.png
  src/main/resources/images/icons8-contacts-64.png
  src/main/resources/images/phone.png
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: type.Enhancement

#87 Add Income Level Field
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditPersonDescriptor.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/IncomeLevel.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/images/dollar.png
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story

#98 Add Monthly Field
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditPersonDescriptor.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Monthly.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/images/monthly.png
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story

#94 Add Risk Tag
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditPersonDescriptor.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/IncomeLevel.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/RiskTag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story

#88 Set maximum appointments for each client and enforce sorting for appointments
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/AddAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/DateTimeParser.java
  src/main/java/seedu/address/logic/parser/EditAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/EditPersonDescriptor.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/util/MaximumSortedList.java
  src/main/java/seedu/address/logic/util/exceptions/SortedListException.java
  src/main/java/seedu/address/model/person/Appointment.java
  src/main/java/seedu/address/model/person/Date.java
  src/main/java/seedu/address/model/person/DateTime.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Time.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/AddAppointmentCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteAppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/util/MaximumSortedListTest.java
  src/test/java/seedu/address/model/person/AppointmentTest.java
  src/test/java/seedu/address/model/person/DateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/TimeTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Enhancement, priority.Medium

#106 Update PersonListPanel color
  src/main/resources/view/DarkTheme.css
Labels: type.Enhancement, severity.VeryLow

#110 Enable assertions
  build.gradle
Labels: type.task, severity.Low

#113 Add testFX library
  build.gradle
Labels: type.Enhancement, severity.Low

#100 Add Calendar Feature to view and schedule appointments
  build.gradle
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/calendar/CalendarEvent.java
  src/main/java/seedu/address/model/calendar/CalendarMonth.java
  src/main/java/seedu/address/model/person/Appointment.java
  src/main/java/seedu/address/model/person/DateTime.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/CalendarDisplay.java
  src/main/java/seedu/address/ui/CalendarEventListPanel.java
  src/main/java/seedu/address/ui/EventButton.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/CalendarDisplay.fxml
  src/main/resources/view/CalendarEventListCard.fxml
  src/main/resources/view/CalendarEventPlaceholder.fxml
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/calendar/CalendarEventTest.java
  src/test/java/seedu/address/model/calendar/CalendarMonthTest.java
  src/test/java/seedu/address/model/person/AppointmentTest.java
  src/test/java/seedu/address/model/person/DateTimeTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/CalendarMonthBuilder.java
Labels: help wanted, work in progress, priority.High

#115 Update Java CI
  .github/workflows/gradle.yml
  build.gradle
Labels: type.Enhancement

#117 Calendar UI
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/CalendarDisplay.java
  src/main/java/seedu/address/ui/CalendarEventListPanel.java
  src/main/java/seedu/address/ui/EventButton.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/CalendarDisplay.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Enhancement

#123 Add aa command User Story and Use Case to Developer Guide
  docs/DeveloperGuide.md
  docs/team/rgonslayer.md
Labels: type.task

#126 Add sort feature to User Guide and Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.task

#125 Update manual testing to Developer Guide
  docs/DeveloperGuide.md
Labels: type.task

#119 Change UI for appointments
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/util/MaximumSortedList.java
  src/main/java/seedu/address/ui/AppointmentFlowPane.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/images/location.png
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/util/MaximumSortedListTest.java
Labels: type.Bug, severity.Low

#127 Update dg
  docs/DeveloperGuide.md
Labels: documentation

#130 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.task

#105 Change Risk Tag colors for different levels of risk
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/SpecialTagLabel.java
  src/main/resources/view/PersonListCard.fxml
Labels: type.Enhancement, severity.Low

#133 Add command history
  .gitignore
  NonExistentFile.txt
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/util/MaximumSortedList.java
  src/main/java/seedu/address/model/CommandHistory.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyCommandHistory.java
  src/main/java/seedu/address/storage/CommandHistoryStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/TextCommandHistoryStorage.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/model/CommandHistoryTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/storage/TextCommandHistoryStorageTest.java
Labels: priority.Medium

#135 Update BetterModelClassDiagram
  docs/diagrams/BetterModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
Labels: documentation, priority.High

#121 Add Calendar Popup
  src/main/java/seedu/address/logic/CalendarLogic.java
  src/main/java/seedu/address/model/calendar/CalendarEvent.java
  src/main/java/seedu/address/ui/AppointmentHBox.java
  src/main/java/seedu/address/ui/CalendarButton.java
  src/main/java/seedu/address/ui/CalendarDisplay.java
  src/main/java/seedu/address/ui/CalendarEventListPanel.java
  src/main/java/seedu/address/ui/CalendarPopup.java
  src/main/java/seedu/address/ui/CalendarPopupContent.java
  src/main/java/seedu/address/ui/EventButton.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/NextButton.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PreviousButton.java
  src/main/java/seedu/address/ui/RefreshButton.java
  src/main/resources/view/AppointmentHBox.fxml
  src/main/resources/view/CalendarDisplay.fxml
  src/main/resources/view/CalendarEventListCard.fxml
  src/main/resources/view/CalendarEventListPanel.fxml
  src/main/resources/view/CalendarEventPlaceholder.fxml
  src/main/resources/view/CalendarPopup.fxml
  src/main/resources/view/CalendarPopupContent.fxml
  src/main/resources/view/EventButton.fxml
  src/main/resources/view/NextButton.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PreviousButton.fxml
  src/main/resources/view/RefreshButton.fxml
Labels: type.task, severity.Medium

#142 Add Sorting by Appointment feature
  docs/images/Ui.png
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/logic/parser/sort/SortByAppointment.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, priority.Medium

#149 Fix button color when selected
  src/main/java/seedu/address/ui/CalendarButton.java
Labels: severity.Low

#152 Fix invalid date bug
  src/main/java/seedu/address/logic/parser/DateTimeParser.java
  src/main/java/seedu/address/model/person/Date.java
  src/main/java/seedu/address/model/person/DateTime.java
Labels: type.Enhancement

#157 Add Plan Tag Feature
  build.gradle
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditPersonDescriptor.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/NormalTag.java
  src/main/java/seedu/address/model/tag/PlanTag.java
  src/main/java/seedu/address/model/tag/RiskTag.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story

#159 Change tags from rectangle to fully rounded and changed padding
  src/main/java/seedu/address/ui/SpecialTagLabel.java
  src/main/resources/view/DarkTheme.css
Labels: severity.Low

#153 Added sort by risk tag feature
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/logic/parser/sort/SortByRiskTag.java
  src/main/java/seedu/address/model/tag/RiskTag.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, priority.Medium

#144 Fix UI text overrun
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/images/calendar.png
  src/main/resources/images/clock.png
  src/main/resources/images/dollar.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: type.Bug, severity.VeryLow

#162 Enhance find command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/NormalTagContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PlanTagContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/RiskTagContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/tag/RiskTag.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.task, type.Story, priority.Medium

#167 Fix double jump bug
  src/main/java/seedu/address/ui/NextButton.java
  src/main/java/seedu/address/ui/PreviousButton.java
  src/main/java/seedu/address/ui/RefreshButton.java
Labels: type.Bug, severity.Low

#138 Add "Add Appointment Command" Sequence Diagram
  docs/DeveloperGuide.md
  docs/diagrams/AddAppointmentCommandSequenceDiagram.puml
  docs/images/AddAppointmentCommandSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/EditPersonDescriptor.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/sort/SortByAppointment.java
  src/main/java/seedu/address/model/person/Appointment.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/MaximumSortedList.java
  src/main/java/seedu/address/model/util/exceptions/SortedListException.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/model/util/MaximumSortedListTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: documentation

#146 Jump calendar feature
  src/main/java/seedu/address/logic/CalendarLogic.java
  src/main/java/seedu/address/model/person/Date.java
  src/main/java/seedu/address/ui/JumpText.java
  src/main/java/seedu/address/ui/TextValidation.java
  src/main/resources/view/JumpText.fxml
  src/main/resources/view/TextValidation.fxml
  src/test/java/seedu/address/model/person/DateTest.java
Labels: enhancement

#173 Update CalendarTabGraphic
  docs/UserGuide.md
  docs/images/CalendarTabGraphic.png
Labels: documentation

#175 Update HelpWindow image and add Add Appointment images in User Guide
  docs/UserGuide.md
  docs/images/AddAppointmentCalendarChange.png
  docs/images/AddAppointmentContactsChange.png
  docs/images/helpMessage.png
Labels: documentation

#177 Update UiClassDiagram, ModelClassDiagram and StorageClassDiagram in Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: documentation

#174 Add sort by monthly contribution feature
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/logic/parser/sort/SortByMonthly.java
  src/main/java/seedu/address/model/person/Monthly.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: type.Story, priority.Medium

#180 Add Calendar features for User Guide
  docs/UserGuide.md
  docs/images/CalendarPopupExample.png
Labels: documentation

#181 Remove refresh button
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/logic/CalendarLogic.java
  src/main/java/seedu/address/ui/RefreshButton.java
  src/main/resources/view/RefreshButton.fxml
Labels: type.Enhancement

#182 Add Calendar figures to User Guide
  docs/UserGuide.md
  docs/images/CalendarPopupExample.png
  docs/images/CalendarWithAppointments.png
  docs/images/EmptyCalendar.png
  docs/images/JumpBox.png
  docs/images/NextButton.png
  docs/images/PreviousButton.png
Labels: documentation

#147 Enable auto-update Calendar on appointment command execution
  src/main/java/seedu/address/logic/CalendarLogic.java
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/calendar/CalendarEvent.java
  src/main/java/seedu/address/ui/CalendarEventListPanel.java
  src/main/resources/view/CalendarPopup.fxml
  src/main/resources/view/EventButton.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Enhancement, priority.Medium

#190 Fix bug where income can't be sorted if value is above max_int
  src/main/java/seedu/address/logic/parser/sort/SortByIncome.java
  src/main/java/seedu/address/model/person/IncomeLevel.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
Labels: type.Bug

#192 Fix bug for calendar logic
  src/main/java/seedu/address/logic/CalendarLogic.java
Labels: type.Bug

#187 Change Help Window Message
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: priority.Medium

#195 Update UG
  docs/UserGuide.md
  docs/images/helpMessage.png
Labels: documentation

#198 Find enhancement
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/IncomeContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
Labels: type.Enhancement

#194 Make horizontal scrollbar align
  src/main/resources/view/PersonListCard.fxml
Labels: type.Bug, severity.VeryLow

#200 Prevent adding consecutive duplicate commands into command history
  docs/UserGuide.md
  src/main/java/seedu/address/model/CommandHistory.java
  src/test/java/seedu/address/model/CommandHistoryTest.java
Labels: type.Bug, severity.Low

#201 Enable multiple prefix in find command
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/FindPredicate.java
  src/main/java/seedu/address/model/person/IncomeContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/MonthlyContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/NormalTagContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PhoneContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PlanTagContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/RiskTagContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/SamePersonPredicate.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: enhancement

#204 Sort client tag
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditPersonDescriptor.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/logic/parser/sort/SortByClientTag.java
  src/main/java/seedu/address/model/person/ClientTagContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/ClientTag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/SpecialTagLabel.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement

#207 Update risk information and add client type information
  docs/UserGuide.md
Labels: documentation
