Repository AY2223S1-CS2103T-W09-2/tp, pull requests merged in 2022-11, with the labels that each got.

#274 Fix Find Command subsequent commands bug and fix test failures
  src/main/java/seedu/address/logic/parser/EditPersonDescriptor.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/tag/ClientTagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug

#280 Bug fix for exceeding the standard 320 characters limit for an email
  src/main/java/seedu/address/model/person/Email.java
  src/test/java/seedu/address/model/person/EmailTest.java
Labels: type.Bug, severity.VeryLow

#279 Bug fix for similar names with white spaces in between
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: type.Bug, severity.VeryLow

#278 Bug Fixes for UG and File Names
  docs/UserGuide.md
  docs/_config.yml
  docs/tutorials/AddRemark.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: documentation

#281 Sort bugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: type.Bug, documentation

#276 Update Project Portfolio Page (Musab)
  docs/team/muhdmusab.md
Labels: documentation

#284 Fix PersonListCard selection issue
  src/main/java/seedu/address/ui/AppointmentHBox.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/PersonListCard.fxml
Labels: type.Bug

#287 Fix Client Tests
  src/main/java/seedu/address/model/person/IncomeLevel.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug

#275 Enable Calendar Navigation when focused on Calendar
  src/main/java/seedu/address/ui/CalendarDisplay.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/CalendarDisplay.fxml
Labels: type.Bug

#290 Fix issue 213
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/IncomeLevel.java
  src/main/java/seedu/address/model/person/Monthly.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/person/IncomeLevelTest.java
  src/test/java/seedu/address/model/person/MonthlyTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug, severity.Medium

#283 Fix name to not allow numerical characters
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/model/person/NameTest.java
Labels: type.Bug

#292 Update GUI graphics
  docs/images/AddAppointmentCalendarChange.png
  docs/images/AddAppointmentContactsChange.png
  docs/images/CalendarTabGraphic.png
  docs/images/ContactsTabGraphic.png
Labels: documentation

#282 Fix Calendar Popup not showing full details
  docs/images/CalendarPopupExample.png
  src/main/java/seedu/address/ui/CalendarPopup.java
  src/main/java/seedu/address/ui/CalendarPopupContent.java
  src/main/java/seedu/address/ui/EventButton.java
  src/main/resources/view/CalendarPopup.fxml
  src/main/resources/view/CalendarPopupContent.fxml
  src/test/java/seedu/address/model/person/EmailTest.java
Labels: type.Bug

#296 Prevent resetting to full client list after executing an appointment command
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
  src/test/java/seedu/address/logic/commands/AddAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteAppointmentCommandTest.java
Labels: type.Bug

#294 Bug fix edit command with no change in details now shows an error message
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: type.Bug, severity.VeryLow

#293 Add contributions to PPP
  docs/team/senwei01.md
Labels: documentation

#298 Update rgonslayer.md
  docs/team/rgonslayer.md
Labels: documentation

#300 Show error message when edit appointment with same location
  src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
  src/test/java/seedu/address/logic/commands/AddAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/EditAppointmentCommandTest.java
Labels: type.Bug

#305 Error for invalid input of date for jump Box
  docs/DeveloperGuide.md
  docs/team/wongyewjon.md
  src/main/java/seedu/address/logic/CalendarLogic.java
  src/main/java/seedu/address/ui/TextValidation.java
Labels: type.Bug, severity.Low

#307 Add PPP
  docs/team/jialatteo.md
Labels: documentation

#308 Fix Jump Box navigation bug
  src/main/java/seedu/address/logic/CalendarLogic.java
  src/main/java/seedu/address/ui/CalendarDisplay.java
  src/main/java/seedu/address/ui/JumpText.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/NextButton.fxml
  src/main/resources/view/PreviousButton.fxml
Labels: type.Bug

#302 Fix Issue 257
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/tag/NormalTag.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: type.Bug, severity.Medium

#310 More specific datetime messages
  src/main/java/seedu/address/logic/parser/AddAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/DateTimeParser.java
  src/main/java/seedu/address/logic/parser/EditAppointmentCommandParser.java
  src/main/java/seedu/address/model/person/DateTime.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddAppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DateTimeParserTest.java
  src/test/java/seedu/address/logic/parser/EditAppointmentCommandParserTest.java
  src/test/java/seedu/address/model/calendar/CalendarMonthTest.java
  src/test/java/seedu/address/model/person/AppointmentTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/testutil/CalendarMonthBuilder.java
Labels: type.Bug

#309 Update User Guide with new date time format
  docs/UserGuide.md
Labels: documentation

#314 Date validation two
  docs/UserGuide.md
  src/main/java/seedu/address/logic/CalendarLogic.java
  src/main/java/seedu/address/ui/TextValidation.java
  src/main/resources/view/JumpText.fxml
Labels: type.Bug, severity.VeryLow

#291 Update Class Diagrams in Developer Guide and refactor Appointment classes into new package
  docs/DeveloperGuide.md
  docs/diagrams/AddAppointmentCommandSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/AddAppointmentCommandSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  src/main/java/seedu/address/logic/CalendarLogic.java
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/AddAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/EditAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/EditAppointmentDescriptor.java
  src/main/java/seedu/address/logic/parser/EditPersonDescriptor.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/Date.java
  src/main/java/seedu/address/model/appointment/DateTime.java
  src/main/java/seedu/address/model/appointment/Location.java
  src/main/java/seedu/address/model/appointment/Time.java
  src/main/java/seedu/address/model/calendar/CalendarEvent.java
  src/main/java/seedu/address/model/person/IncomeLevel.java
  src/main/java/seedu/address/model/person/Monthly.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/AppointmentHBox.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/AddAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/EditAppointmentCommandTest.java
  src/test/java/seedu/address/logic/parser/AddAppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditAppointmentCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/calendar/CalendarEventTest.java
  src/test/java/seedu/address/model/calendar/CalendarMonthTest.java
  src/test/java/seedu/address/model/person/AppointmentTest.java
  src/test/java/seedu/address/model/person/DateTest.java
  src/test/java/seedu/address/model/person/DateTimeTest.java
  src/test/java/seedu/address/model/person/LocationTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/TimeTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedAppointmentTest.java
  src/test/java/seedu/address/testutil/AppointmentBuilder.java
  src/test/java/seedu/address/testutil/CalendarMonthBuilder.java
  src/test/java/seedu/address/testutil/EditAppointmentDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: documentation

#315 Fix find and edit command bugs
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/IncomeContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/IncomeLevel.java
  src/main/java/seedu/address/model/person/MonthlyContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/tag/PlanTag.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/tag/RiskTagTest.java
Labels: type.Bug

#321 Uml diagram
  docs/DeveloperGuide.md
  docs/diagrams/CalendarDisplayActivityDiagram.puml
  docs/diagrams/CalendarNavigationActivityDiagram.puml
  docs/diagrams/CalendarPopUpActivityDiagram.puml
  docs/diagrams/DeleteAppointmentCommandSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/CalendarDisplayActivityDiagram.png
  docs/images/CalendarNavigationActivityDiagram.png
  docs/images/CalendarPopUpActivityDiagram.png
  docs/images/DeleteAppointmentCommandSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: documentation

#323 Add Find Command to Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/AddAppointmentCommandSequenceDiagram.puml
  docs/diagrams/FindCommandActivityDiagram.puml
  docs/images/AddAppointmentCommandSequenceDiagram.png
  docs/images/CalendarTabGraphic.png
  docs/images/ContactsTabGraphic.png
  docs/images/FindCommandActivityDiagram.png
Labels: documentation

#325 Update Help window
  docs/UserGuide.md
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: type.Bug, documentation, severity.VeryLow

#326 Update Find Hint
  src/main/java/seedu/address/logic/commands/FindCommand.java
Labels: type.Bug, severity.Low

#327 Update UG
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/helpMessage.png
Labels: documentation

#329 Prefix update
  docs/UserGuide.md
Labels: documentation

#330 Update DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/SortCommandActivityDiagram.puml
  docs/diagrams/SortCommandSequenceDiagram.puml
  docs/images/SortCommandActivityDiagram.png
  docs/images/SortCommandSequenceDiagram.png
  docs/team/muhdmusab.md
  docs/team/rgonslayer.md
  docs/team/senwei01.md
  docs/team/wongyewjon.md
Labels: documentation

#331 Update Calendar feature class diagram
  docs/DeveloperGuide.md
  docs/diagrams/CalendarUiClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/CalendarUiClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: documentation

#322 Fix fields currently allowing multiple whitespaces
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/tag/PlanTag.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: type.Bug

#332 Update calendar pictures
  docs/UserGuide.md
  docs/images/AddAppointmentCalendarChange.png
  docs/images/AddAppointmentContactsChange.png
  docs/images/CalendarPopupExample.png
  docs/images/CalendarWithAppointments.png
  docs/images/EmptyCalendar.png
  docs/images/JumpBox.png
  docs/images/NextButton.png
  docs/images/PreviousButton.png
Labels: documentation

#333 Crop picture
  docs/images/AddAppointmentCalendarChange.png
  docs/images/AddAppointmentContactsChange.png
Labels: documentation

#335 Update Calendar in Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/CalendarLogicClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/images/CalendarLogicClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/team/muhdmusab.md
  src/main/java/seedu/address/logic/CalendarLogic.java
  src/main/java/seedu/address/ui/CalendarDisplay.java
  src/main/java/seedu/address/ui/JumpBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/CalendarDisplay.fxml
  src/main/resources/view/JumpBox.fxml
  src/main/resources/view/JumpText.fxml
Labels: documentation

#328 Refactor Tags
  src/main/java/seedu/address/model/tag/ClientTag.java
  src/main/java/seedu/address/model/tag/NormalTag.java
  src/main/java/seedu/address/model/tag/PlanTag.java
  src/main/java/seedu/address/model/tag/RiskTag.java
  src/main/java/seedu/address/model/tag/SpecialTag.java
Labels: type.Bug

#337 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/AddCommandSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/EditCommandSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/AddCommandSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/EditCommandSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditPersonDescriptor.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Income.java
  src/main/java/seedu/address/model/person/IncomeContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/IncomeLevelTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: documentation

#336 Update ppp
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/muhdmusab.md
  docs/team/wongyewjon.md
  src/main/java/seedu/address/logic/CalendarLogic.java
Labels: documentation

#341 Update ppp
  docs/DeveloperGuide.md
  docs/team/wongyewjon.md
Labels: documentation
